[package]
name = "rsos"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["staticlib"]

[dependencies]
multiboot2 = { version = "0.20.2", default-features = false, features = [
    "unstable",
] }
spin = "0.9.8"

[dependencies.lazy_static]
version = "1.5.0"
features = ["spin_no_std"]
